image: Ubuntu1804 # образ для сборки
stack: node 16 # окружение
branches: 
  only:
    - master # ветка гит
cache: node_modules # кеширование
install: 
  - npm i # командка установки зависимостей    
build: off
test_script:
  - npm run lint && npm test # скрипт сборки
